### ISSUE TITLE
Typo (“excercise”)

### ISSUE THREAD

**Issue by djbpitt** [ebeshero/DigMitCS#5]
https://github.com/ebeshero/DigMitCS/blob/f2c8720e95726cc154eaedb3e868fa3d53df0dd1/docs/_includes/Monday2018.html#L47

**Comment by ebeshero** [comment]
Thank you! Resolved with https://github.com/ebeshero/DigMitCS/commit/14dd718ea1152ac4a17dcf66e4cb8a970aebe65c
